// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeagjydtlouovkgrrbny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lYWdqeWR0bG91b3ZrZ3JyYm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDEwNzcsImV4cCI6MjA2NDExNzA3N30.oV5k2Kb8bFKX-cus89lo9ey5AnRJezhJCKW_cPh2qeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);